from django.urls import path
from . import views

urlpatterns = [

    path('moviescript', views.main, name='main'),
    path('moviescript/', views.main, name='main'),
    path('moviescript/update', views.update, name='update'),
    path('moviescript/delete', views.delete, name='delete'),
    path('moviescript/instructions', views.instructions, name='instructions'),

    # for login
    path('moviescript/signup', views.signup, name='signup'),
    path('moviescript/signup/', views.signup, name='signup'),
    path('moviescript/signup/user_duplication_check', views.user_duplication_check,
         name='user_duplication_check'),
    # path('/signup/signup_after', views.signup_after, name='signup_after'),
    path('moviescript/login', views.login, name='login'),
    path('moviescript/login/', views.login, name='login'),
    path('moviescript/logout/', views.logout, name='logout'),
    path('moviescript/logout', views.logout, name='logout'),

    # 유저정보수정
    path('moviescript/account', views.account, name='account'),
    path('moviescript/forgot_password', views.forgot_password, name='forgot_password'),
    path('moviescript/reset_password', views.reset_password, name='reset_password'),

    # 영화 페이지
    path('moviescript/8월의크리스마스', views.팔월의크리스마스, name='8월의크리스마스'),
    path('moviescript/7급공무원', views.칠급공무원, name='7급공무원'),
    path('moviescript/ing', views.ing, name='ing'),
    path('moviescript/m', views.m, name='m'),
    path('moviescript/ymca야구단', views.ymca야구단, name='ymca야구단'),
    path('moviescript/가면', views.가면, name='가면'),
    path('moviescript/가문의영광', views.가문의영광, name='가문의영광'),
    path('moviescript/가위', views.가위, name='가위'),
    path('moviescript/가을로', views.가을로, name='가을로'),
    path('moviescript/가족', views.가족, name='가족'),
    path('moviescript/가족의탄생', views.가족의탄생, name='가족의탄생'),
    path('moviescript/각설탕', views.각설탕, name='각설탕'),
    path('moviescript/간신', views.간신, name='간신'),
    path('moviescript/간첩리철진', views.간첩리철진, name='간첩리철진'),
    path('moviescript/강원도의힘', views.강원도의힘, name='강원도의힘'),
    path('moviescript/강철중', views.강철중, name='강철중'),
    path('moviescript/거룩한계보', views.거룩한계보, name='거룩한계보'),
    path('moviescript/거미숲', views.거미숲, name='거미숲'),
    path('moviescript/거울속으로', views.거울속으로, name='거울속으로'),
    path('moviescript/건축무한육면각체의비밀', views.건축무한육면각체의비밀, name='건축무한육면각체의비밀'),
    path('moviescript/건축학개론', views.건축학개론, name='건축학개론'),
    path('moviescript/결혼은미친짓이다', views.결혼은미친짓이다, name='결혼은미친짓이다'),
    path('moviescript/고사', views.고사, name='고사'),
    path('moviescript/고양이를부탁해', views.고양이를부탁해, name='고양이를부탁해'),
    path('moviescript/고지전', views.고지전, name='고지전'),
    path('moviescript/곡성', views.곡성, name='곡성'),
    path('moviescript/공공의적', views.공공의적, name='공공의적'),
    path('moviescript/공공의적2', views.공공의적2, name='공공의적2'),
    path('moviescript/공동경비구역JSA', views.공동경비구역JSA, name='공동경비구역JSA'),
    path('moviescript/광식이동생광태', views.광식이동생광태, name='광식이동생광태'),
    path('moviescript/괴물', views.괴물, name='괴물'),
    path('moviescript/국가대표', views.국가대표, name='국가대표'),
    path('moviescript/국화꽃향기', views.국화꽃향기, name='국화꽃향기'),
    path('moviescript/귀여워', views.귀여워, name='귀여워'),
    path('moviescript/그녀를믿지마세요', views.그녀를믿지마세요, name='그녀를믿지마세요'),
    path('moviescript/그놈은멋있었다', views.그놈은멋있었다, name='그놈은멋있었다'),
    path('moviescript/그림자살인', views.그림자살인, name='그림자살인'),
    path('moviescript/그해여름', views.그해여름, name='그해여름'),
    path('moviescript/극락도살인사건', views.극락도살인사건, name='극락도살인사건'),
    path('moviescript/꽃잎', views.꽃잎, name='꽃잎'),
    path('moviescript/꽃피는봄이오면', views.꽃피는봄이오면, name='꽃피는봄이오면'),
    path('moviescript/끝까지간다', views.끝까지간다, name='끝까지간다'),
    path('moviescript/나도아내가있었으면좋겠다', views.나도아내가있었으면좋겠다, name='나도아내가있었으면좋겠다'),
    path('moviescript/나의결혼원정기', views.나의결혼원정기, name='나의결혼원정기'),
    path('moviescript/남극일기', views.남극일기, name='남극일기'),
    path('moviescript/내깡패같은애인', views.내깡패같은애인, name='내깡패같은애인'),
    path('moviescript/내마음의풍금', views.내마음의풍금, name='내마음의풍금'),
    path('moviescript/내머리속의지우개', views.내머리속의지우개, name='내머리속의지우개'),
    path('moviescript/내생애가장아름다운일주일', views.내생애가장아름다운일주일, name='내생애가장아름다운일주일'),
    path('moviescript/내심장을쏴라', views.내심장을쏴라, name='내심장을쏴라'),
    path('moviescript/너는내운명', views.너는내운명, name='너는내운명'),
    path('moviescript/넘버3', views.넘버3, name='넘버3'),
    path('moviescript/누가그녀와잤을까', views.누가그녀와잤을까, name='누가그녀와잤을까'),
    path('moviescript/눈물', views.눈물, name='눈물'),
    path('moviescript/눈에는눈이에는이', views.눈에는눈이에는이, name='눈에는눈이에는이'),
    path('moviescript/다세포소녀', views.다세포소녀, name='다세포소녀'),
    path('moviescript/다찌마와리', views.다찌마와리, name='다찌마와리'),
    path('moviescript/단적비연수', views.단적비연수, name='단적비연수'),
    path('moviescript/달마야놀자', views.달마야놀자, name='달마야놀자'),
    path('moviescript/달콤살벌한연인', views.달콤살벌한연인, name='달콤살벌한연인'),
    path('moviescript/달콤한인생', views.달콤한인생, name='달콤한인생'),
    path('moviescript/대한민국헌법제1조', views.대한민국헌법제1조, name='대한민국헌법제1조'),
    path('moviescript/뜨거운것이좋아', views.뜨거운것이좋아, name='뜨거운것이좋아'),
    path('moviescript/파이란', views.파이란, name='파이란'),
    path('moviescript/마이제너레이션', views.마이제너레이션, name='마이제너레이션'),
    path('moviescript/여고괴담2', views.여고괴담2, name='여고괴담2'),
    path('moviescript/박하사탕', views.박하사탕, name='박하사탕'),
    path('moviescript/수취인불명', views.수취인불명, name='수취인불명'),
    path('moviescript/싱글즈', views.싱글즈, name='싱글즈'),
    path('moviescript/오수정', views.오수정, name='오수정'),
    path('moviescript/올드보이', views.올드보이, name='올드보이'),
    path('moviescript/우아한거짓말', views.우아한거짓말, name='우아한거짓말'),
    path('moviescript/유령', views.유령, name='유령'),
    path('moviescript/이중간첩', views.이중간첩, name='이중간첩'),
    path('moviescript/추격자', views.추격자, name='추격자'),
    path('moviescript/커밍아웃', views.커밍아웃, name='커밍아웃'),
    path('moviescript/파란대문', views.파란대문, name='파란대문'),
    path('moviescript/페이스', views.페이스, name='페이스'),
    path('moviescript/하루', views.하루, name='하루'),
    path('moviescript/행복한장의사', views.행복한장의사, name='행복한장의사'),
]
