# Generated by Django 3.0.8 on 2021-07-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_script', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotation_key',
            field=models.IntegerField(null=True),
        ),
    ]
